//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_V1.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PWD { get; set; }
        public string Mobile { get; set; }
        public string DeliveryAddress { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
        public string UserId { get; set; }
        public string ProfileImage { get; set; }
    }
}
